### PR TITLE
Update start_reservation.py

### PR DESCRIPTION
**Pull request by DYeag**
update start reservation with sandbox api

### CODE REVIEW

**Comment by brennerm** [comment]
@DYeag Please resolve the merge conflicts. Afterwards I'll start to work on the TODOs.

**Comment by brennerm** [comment]
@DYeag When testing the authentication code against our Cloudshell instance I get the following response:
```
<Response [404]>
Basic {
  Message: Not Supported
}
```
Any idea what's going wrong here?

**Review by shivamcandela — COMMENTED** [review]
@DYeag Can you please update this PR. if we don't need this anymore, can we close this PR?

**Comment by shivamcandela** [comment]
Closing the PR as no activity

**Pull request closed without merging**
